//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculatedTax
    {
        public int Id { get; set; }
        public Nullable<int> TaxCalculated { get; set; }
        public string DateStmp { get; set; }
        public string PoastalCode { get; set; }
        public Nullable<int> AnnualIncome { get; set; }
    }
}
